language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  - pushd app_camera_support/
  - pub get
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
  - popd
script:
  - pushd app_camera_support/
  - dart tool/run_ci.dart
# matrix:
#  allow_failures:
#    - dart: dev